Configurable newlines between declarations
parsonsmatt/fourmolu pull request #48
Opened 2020-10-09 18:19 UTC by wraithm

The number of newlines between declarations can now be configured with 'newlines-between-decls' configuration option.

Closes #47 

This does exactly what I want! It's idempotent as well. It defaults to exactly ormolu behavior. I tested it on our large industrial codebase. I don't see anything unexpected from my initial skim. If we merge this, I think we'd start using this at @bitnomial.

2020-10-09 18:20 UTC, wraithm commented
@georgefst @parsonsmatt What do you think?

2020-10-09 18:25 UTC, wraithm commented
Also, all tests pass.

2020-10-09 18:30 UTC, parsonsmatt commented
I'm happy to support a style that you like!

2020-10-13 13:28 UTC, georgefst requested changes
This is great, and simpler than I expected. Just a few minor things.

2020-10-13 13:28 UTC, georgefst commented on src/Ormolu/Printer/Meat/Declaration.hs
> +            then declBreakpoint : renderGroup curr
These `breakpoint`s could actually have been `newline` since we never print declarations on a single line. This means they can now be `declNewline`, and `declBreakpoint` needn't exist.

2020-10-13 13:28 UTC, georgefst commented on src/Ormolu/Printer/Internal.hs
> +          scRequestedDelimiter = case requestedDel of
I agree this is slightly cleaner, but since this function is otherwise untouched by this PR it should be reverted.

2020-10-13 13:28 UTC, georgefst commented on src/Ormolu/Printer/Internal.hs
> +
There's a bit of repetition here with `newlineRaw`. Is there a good reason why this can't be written in such a way that `newlineRaw = newlineRawN 1`?

2020-10-13 13:28 UTC, georgefst commented on src/Ormolu/Printer/Meat/Module.hs
> +    declNewline
Curiously, the tests pass even with this line omitted entirely...

2020-10-13 13:29 UTC, georgefst commented on src/Ormolu/Printer/Meat/Module.hs
> +    declNewline
(I'm not suggesting actually changing anything here)

2020-10-13 16:10 UTC, wraithm commented on src/Ormolu/Printer/Internal.hs
> +          scRequestedDelimiter = case requestedDel of
Of course! Yeah, I got overeager 👍

2020-10-13 16:10 UTC, wraithm commented on src/Ormolu/Printer/Meat/Declaration.hs
> +            then declBreakpoint : renderGroup curr
👍 np

2020-10-13 17:32 UTC, wraithm commented on src/Ormolu/Printer/Meat/Module.hs
> +    declNewline
Redundant because two `newline` calls in a row is only one `newline`.

2020-10-13 17:39 UTC, wraithm commented on src/Ormolu/Printer/Internal.hs
> +
This is a great question. It all comes down to what these cases mean when there's no newline:

```
        { scBuilder = case requestedDel of
            AfterNewline -> builderSoFar
            RequestedNewline -> builderSoFar
            VeryBeginning -> builderSoFar
            _ -> builderSoFar <> "\n",
```

In my version of `newlineRawN`, I add newlines regardless of the value of `scRequestedDelimiter sc` is. In `newlineRaw`, `AfterNewline`, `RequestedNewline`, and `VeryBeginning` get nothing. Perhaps my version shouldn't do anything on `VeryBeginning` either, but I think because I'm explicitly trying to violate the invariant that `AfterNewline` and `RequestedNewline` newlines do nothing, it needs to be a separate function if we're going to maintain standard `ormolu` formatting in the body of functions or instance declarations or any other thing which might have multiple calls to `newlineRaw`, but want to not generate a newline.

I tried modifying `newlineRaw` to get the right behavior, but I couldn't really do it... Maybe the "correct" way to solve this problem is to have a new `scRequestedDelimiter` type which handles the end of declarations or something like that. However, I think that would be a pretty massive overhaul to the internals of ormolu that might not yield the right solution.

2020-10-13 17:47 UTC, wraithm commented
Okay @georgefst, I responded to all comments and pushed your requested changes 👍

2020-10-13 20:29 UTC, georgefst commented on src/Ormolu/Printer/Internal.hs
> +
I couldn't resist tinkering with this. See 071951f.

It's quite easy to see, via equational reasoning, that the new `newlineRaw` is equivalent to the old one.

And that commit doesn't change the behaviour with `poNewlinesBetweenDecls = 2` for anything in our, pretty extensive, test suite, so I'm fairly sure it's safe. But you may want to test with your own code.

2020-10-13 20:45 UTC, wraithm commented on src/Ormolu/Printer/Internal.hs
> +
Okay! I'll do a test.

2020-10-13 20:53 UTC, georgefst commented
Ok @wraithm, I'll merge if you're happy with my new changes.

2020-10-13 20:53 UTC, wraithm commented on src/Ormolu/Printer/Internal.hs
> +
@georgefst This works great for me. I love it.

2020-10-13 20:54 UTC, wraithm commented
@georgefst I'm very happy. Go ahead!

2020-10-13 20:56 UTC, merged

2020-10-13 20:57 UTC, wraithm commented
🎉 Thanks!

2020-10-13 20:59 UTC, wraithm commented
@georgefst Would you mind making a hackage publish at some point soon? We're gonna convert to fourmolu at @bitnomial asap.

2020-10-13 21:04 UTC, georgefst commented
I suppose we could make a release with this and #44, which I'll hopefully get merged today.

I think PVP forces this to be a major release since it adds a record field (although I'd be surprised if Fourmolu were actually being used as a library anywhere other than in HLS, which I know wont be broken by this).

2020-10-13 22:36 UTC, georgefst commented
@wraithm [Done.](https://hackage.haskell.org/package/fourmolu-0.3.0.0/docs/Ormolu-Config.html#t:PrinterOpts)

2020-10-13 22:37 UTC, wraithm commented
You the best. Thanks!