Fix multiline haddocks in indented contexts
parsonsmatt/fourmolu pull request #64
Opened 2021-03-04 00:59 UTC by brandon-leapyear

2021-03-04 23:43 UTC, georgefst requested changes
This looks great. Thanks!

Just the minor quibble on whitespace.

2021-03-04 23:43 UTC, georgefst commented on src/Ormolu/Printer/Meat/Common.hs
> +
I agree this is nicer with a few more line breaks. But I'm very weary of doing anything which unnecessarily increases the diff with upstream. Merging a new Ormolu version can be quite hairy already.

2021-03-04 23:45 UTC, brandon-leapyear commented on src/Ormolu/Printer/Meat/Common.hs
> +
oof. completely understand. will revert

2021-03-04 23:49 UTC, merged

2021-03-13 18:58 UTC, brandon-leapyear commented
@georgefst is this fix worth a patch release to hackage?

2021-03-13 19:37 UTC, georgefst commented
We should hopefully be able to batch this up with a few other upcoming changes. Unless you could really do with it on Hackage for any reason?

2021-03-13 19:40 UTC, brandon-leapyear commented
If there are upcoming changes, then it can wait. As long as there's some release within a few weeks?

2021-05-13 10:02 UTC, gustavoavena commented
Is there an ETA for when this fix will be released?
Thanks!

2021-06-02 22:39 UTC, brandon-leapyear commented
@georgefst any updates on a Hackage release?